/**
 * Auto-generated context files — writes CLAUDE.md and .cursorrules
 * to each workspace on every scan.
 *
 * These files give AI assistants (Claude Code, Cursor, Copilot) automatic
 * awareness of workspace state without requiring MCP. The Hub becomes
 * invisible infrastructure that enriches AI tool context natively.
 *
 * Generated files include:
 * - Workspace overview (groups, artifact counts)
 * - Recently changed docs
 * - Stale docs needing attention
 * - Hygiene issue summary
 * - Active decisions
 */

import { writeFileSync, existsSync, readFileSync } from "fs";
import { join } from "path";
import type { Manifest } from "./types";

// ── Types ──────────────────────────────────────────────────────────

export interface ContextFileResult {
  workspace: string;
  claudeMdWritten: boolean;
  cursorRulesWritten: boolean;
  error?: string;
}

// ── Config ─────────────────────────────────────────────────────────

const MARKER = "<!-- auto-generated by the-hub -->";

/**
 * Check if a file was generated by The Hub (has our marker).
 * If a user-created file exists without the marker, we don't overwrite it.
 */
function isHubGenerated(filePath: string): boolean {
  if (!existsSync(filePath)) return true; // doesn't exist yet, safe to write
  try {
    const content = readFileSync(filePath, "utf8");
    return content.includes(MARKER);
  } catch {
    return false;
  }
}

// ── Generator ──────────────────────────────────────────────────────

/**
 * Generate context content for a workspace.
 */
export function generateContextContent(manifest: Manifest, workspacePath: string): string {
  const wsArtifacts = manifest.artifacts.filter((a) => {
    // Match artifacts belonging to this workspace
    // Artifact paths are relative — check if they could belong here
    return true; // Include all artifacts for now (single-workspace common case)
  });

  const parts: string[] = [];
  parts.push(MARKER);
  parts.push(`# Workspace Context`);
  parts.push(`\n> Auto-generated by [The Hub](https://github.com/ahmedkhaledmohamed/the-hub) on ${new Date().toISOString().slice(0, 16)}. Do not edit manually — regenerated on every scan.\n`);

  // Overview
  parts.push(`## Overview`);
  parts.push(`- **${wsArtifacts.length} artifacts** across **${manifest.groups.length} groups**`);
  parts.push(`- Last scan: ${manifest.generatedAt}`);

  // Groups
  if (manifest.groups.length > 0) {
    parts.push(`\n## Groups`);
    for (const g of manifest.groups) {
      parts.push(`- **${g.label}** (${g.id}): ${g.count} artifacts${g.description ? ` — ${g.description}` : ""}`);
    }
  }

  // Recently changed (last 7 days, top 10)
  const recent = wsArtifacts
    .filter((a) => a.staleDays <= 7)
    .sort((a, b) => a.staleDays - b.staleDays)
    .slice(0, 10);
  if (recent.length > 0) {
    parts.push(`\n## Recently Changed`);
    for (const a of recent) {
      parts.push(`- \`${a.path}\` — ${a.title} (${a.staleDays === 0 ? "today" : `${a.staleDays}d ago`})`);
    }
  }

  // Stale docs (top 10)
  const stale = wsArtifacts
    .filter((a) => a.staleDays > 90)
    .sort((a, b) => b.staleDays - a.staleDays)
    .slice(0, 10);
  if (stale.length > 0) {
    parts.push(`\n## Needs Attention (${wsArtifacts.filter((a) => a.staleDays > 90).length} stale)`);
    for (const a of stale) {
      parts.push(`- \`${a.path}\` — ${a.title} (${a.staleDays} days old)`);
    }
  }

  // Hygiene summary
  try {
    const { getCachedHygieneSummary } = require("./hygiene-analyzer");
    const hygiene = getCachedHygieneSummary();
    if (hygiene && hygiene.totalFindings > 0) {
      parts.push(`\n## Hygiene Issues: ${hygiene.totalFindings} finding(s)`);
      if (hygiene.highCount > 0) parts.push(`- ${hygiene.highCount} high severity`);
      if (hygiene.mediumCount > 0) parts.push(`- ${hygiene.mediumCount} medium severity`);
      if (hygiene.lowCount > 0) parts.push(`- ${hygiene.lowCount} low severity`);
    }
  } catch { /* non-critical */ }

  // Active decisions (top 5)
  try {
    const { getActiveDecisions, getDecisionCounts } = require("./decision-tracker");
    const counts = getDecisionCounts();
    if (counts.active > 0) {
      const decisions = getActiveDecisions(5);
      parts.push(`\n## Active Decisions (${counts.active} total)`);
      for (const d of decisions) {
        parts.push(`- ${d.summary} — \`${d.artifactPath}\``);
      }
    }
  } catch { /* non-critical */ }

  parts.push(""); // trailing newline
  return parts.join("\n");
}

/**
 * Generate .cursorrules content (more concise, instruction-focused).
 */
export function generateCursorRulesContent(manifest: Manifest): string {
  const parts: string[] = [];
  parts.push(MARKER);
  parts.push(`# Workspace Rules (auto-generated by The Hub)`);
  parts.push(`# Regenerated on every scan. Do not edit manually.`);
  parts.push(``);
  parts.push(`# ${manifest.artifacts.length} artifacts across ${manifest.groups.length} groups`);
  parts.push(`# Last scan: ${manifest.generatedAt}`);

  // Group overview as comments
  if (manifest.groups.length > 0) {
    parts.push(``);
    parts.push(`# Groups:`);
    for (const g of manifest.groups) {
      parts.push(`# - ${g.label} (${g.id}): ${g.count} artifacts`);
    }
  }

  // Stale warning
  const staleCount = manifest.artifacts.filter((a) => a.staleDays > 90).length;
  if (staleCount > 0) {
    parts.push(``);
    parts.push(`# WARNING: ${staleCount} stale documents (>90 days). Check hygiene.`);
  }

  parts.push(""); // trailing newline
  return parts.join("\n");
}

/**
 * Write context files to a workspace directory.
 * Only writes if the file doesn't exist or was previously generated by Hub.
 */
export function writeContextFiles(
  manifest: Manifest,
  workspacePath: string,
): ContextFileResult {
  const result: ContextFileResult = {
    workspace: workspacePath,
    claudeMdWritten: false,
    cursorRulesWritten: false,
  };

  if (!existsSync(workspacePath)) {
    result.error = "Workspace path does not exist";
    return result;
  }

  // Write .hub-context.md (not CLAUDE.md — avoid overwriting user files)
  const contextPath = join(workspacePath, ".hub-context.md");
  if (isHubGenerated(contextPath)) {
    try {
      writeFileSync(contextPath, generateContextContent(manifest, workspacePath), "utf8");
      result.claudeMdWritten = true;
    } catch (err) {
      result.error = `Failed to write ${contextPath}: ${(err as Error).message}`;
    }
  }

  // Write .cursorrules only if Hub-generated or doesn't exist
  const cursorPath = join(workspacePath, ".cursorrules");
  if (isHubGenerated(cursorPath)) {
    try {
      writeFileSync(cursorPath, generateCursorRulesContent(manifest), "utf8");
      result.cursorRulesWritten = true;
    } catch (err) {
      result.error = (result.error ? result.error + "; " : "") + `Failed to write ${cursorPath}: ${(err as Error).message}`;
    }
  }

  return result;
}

/**
 * Write context files to all configured workspaces.
 * Called automatically after each scan.
 */
export function writeContextFilesToAllWorkspaces(manifest: Manifest): ContextFileResult[] {
  const results: ContextFileResult[] = [];

  for (const wsPath of manifest.workspaces) {
    results.push(writeContextFiles(manifest, wsPath));
  }

  return results;
}
